services:
  # PostgreSQL service
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  # FastAPI service
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    depends_on:
      - postgres
    environment:
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      HOST: ${HOST}
      PORT: ${PORT}
      DATABASE: ${DATABASE}
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: