from sqlalchemy import BigInteger, Integer, Text, Column, DateTime, Float, String
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Fifa(Base):
    __tablename__ = "Fifa17_table"

    ID = Column(BigInteger, primary_key=True, nullable=False)
    Name = Column(String)
    Age = Column(Integer)
    Photo = Column(String)
    Nationality = Column(String)
    Flag = Column(String)
    Overall = Column(Integer)
    Potential = Column(Integer)
    Club = Column(String)
    ClubLogo = Column(String)
    Value = Column(String)
    Wage = Column(String)
    Special = Column(String)
    PreferredFoot = Column(String)
    InternationalReputation = Column(Float)
    WeakFoot = Column(String)
    SkillMoves = Column(Float)
    WorkRate = Column(String)
    BodyType = Column(String)
    RealFace = Column(String)
    Position = Column(String)
    JerseyNumber = Column(Float)
    Joined = Column(Text)
    LoanedFrom = Column(Text)
    ContractValidUntil = Column(Text)
    Height = Column(String)
    Weight = Column(String)
    Crossing = Column(Float)
    Finishing = Column(Float)
    HeadingAccuracy = Column(Float)
    ShortPassing = Column(Float)
    Volleys = Column(Float)
    Dribbling = Column(Float)
    Curve = Column(Float)
    FKAccuracy = Column(Float)
    LongPassing = Column(Float)
    BallControl = Column(Float)
    Acceleration = Column(Float)
    SprintSpeed = Column(Float)
    Agility = Column(Float)
    Reactions = Column(Float)
    Balance = Column(Float)
    ShotPower = Column(Float)
    Jumping = Column(Float)
    Stamina = Column(Float)
    Strength = Column(Float)
    LongShots = Column(Float)
    Aggression = Column(Float)
    Interceptions = Column(Float)
    Positioning = Column(Float)
    Vision = Column(Float)
    Penalties = Column(Float)
    Composure = Column(Float)
    Marking = Column(Float)
    StandingTackle = Column(Float)
    SlidingTackle = Column(Float)
    GKDiving = Column(Float)
    GKHandling = Column(Float)
    GKKicking = Column(Float)
    GKPositioning = Column(Float)
    GKReflexes = Column(Float)
    BestPosition = Column(String)
    BestOverallRating = Column(Float)
